# Generated by Django 5.2 on 2025-04-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaivariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chai_type', models.CharField(choices=[('ml', 'masala chai'), ('sp', 'spiced chai'), ('ch', 'chai latte'), ('g', 'ginger chai'), ('l', 'lemon chai'), ('m', 'mint chai'), ('s', 'spiced chai'), ('c', 'chai latte'), ('t', 'chai tea'), ('p', 'peppermint chai'), ('h', 'honey chai'), ('g', 'ginger chai')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
