# Generated by Django 5.2 on 2025-04-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
