# Generated by Django 5.2 on 2025-04-15 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_alter_chaivariety_chai_type_chaicertificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaivariety',
            options={'verbose_name_plural': 'Chai Varieties'},
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
