# Generated by Django 5.2 on 2025-04-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_alter_chaivariety_options_chaivariety_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaivariety',
            name='date_added',
        ),
    ]
