# Generated by Django 5.2 on 2025-04-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0006_store_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(default='media/images/default.jpg', upload_to='images/'),
        ),
    ]
