# Generated by Django 5.2 on 2025-04-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0007_alter_store_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
