# Generated by Django 5.2 on 2025-04-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0008_alter_store_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
